### ISSUE TITLE
user-can-turn-car

### ISSUE THREAD

**Issue by josh-choi94** [josh-choi94/driving-game#3]
## ✅ Task List

- [x] add html class names
- [x] add javascript function to turn vehicle
- [x] check for correct directions
- [x] css class directions needed
